export const actionTypes = {
    DANG_NHAP:'DANG_NHAP',
    DANG_KY:'DANG_KY',
    DANG_XUAT:'DANG_XUAT',
    LAY_DANH_SACH_NGUOI_TAO:'LAY_DANH_SACH_NGUOI_TAO',
    LAY_DANH_SACH_NGUOI_DUNG : 'LAY_DANH_SACH_NGUOI_DUNG',
    LAY_THONG_TIN_TAI_KHOAN : 'LAY_THONG_TIN_TAI_KHOAN',
    LAY_DANH_SACH_LOAI_NGUOI_DUNG : 'LAY_DANH_SACH_LOAI_NGUOI_DUNG',
    
}
