export const actionTypes = {
    DANG_NHAP: 'DANG_NHAP',
    DANG_KY: 'DANG_KY',
    DANG_XUAT: 'DANG_XUAT',
    LAY_DANH_SACH_NGUOI_TAO: 'LAY_DANH_SACH_NGUOI_TAO',
    LAY_DANH_SACH_NGUOI_DUNG: 'LAY_DANH_SACH_NGUOI_DUNG',
    LAY_DANH_SACH_NGUOI_DUNG_PHAN_TRANG : 'LAY_DANH_SACH_NGUOI_DUNG_PHAN_TRANG',
    LAY_THONG_TIN_TAI_KHOAN: 'LAY_THONG_TIN_TAI_KHOAN',
    LAY_DANH_SACH_LOAI_NGUOI_DUNG: 'LAY_DANH_SACH_LOAI_NGUOI_DUNG',

    LAY_DANH_SACH_HOC_VIEN_CHO_XET_DUYET_DUA_VAO_KHOA_HOC : 'LAY_DANH_SACH_HOC_VIEN_CHO_XET_DUYET_DUA_VAO_KHOA_HOC',
    LAY_DANH_SACH_HOC_VIEN_DA_XET_DUYET_DUA_VAO_KHOA_HOC : 'LAY_DANH_SACH_HOC_VIEN_DA_XET_DUYET_DUA_VAO_KHOA_HOC',
    LAY_DANH_SACH_HOC_VIEN_CHUA_XET_DUYET_DUA_VAO_KHOA_HOC : 'LAY_DANH_SACH_HOC_VIEN_CHUA_XET_DUYET_DUA_VAO_KHOA_HOC',

    LAY_DANH_SACH_KHOA_HOC_CHO_XET_DUYET_DUA_VAO_HOC_VIEN :'LAY_DANH_SACH_KHOA_HOC_CHO_XET_DUYET_DUA_VAO_HOC_VIEN',
    LAY_DANH_SACH_KHOA_HOC_DA_XET_DUYET_DUA_VAO_HOC_VIEN : 'LAY_DANH_SACH_KHOA_HOC_DA_XET_DUYET_DUA_VAO_HOC_VIEN',
    LAY_DANH_SACH_KHOA_HOC_CHUA_XET_DUYET_DUA_VAO_HOC_VIEN : 'LAY_DANH_SACH_KHOA_HOC_CHUA_XET_DUYET_DUA_VAO_HOC_VIEN',

    TIM_KIEM_NGUOI_DUNG: 'TIM_KIEM_NGUOI_DUNG',
}
