export const actionTypes =
{
  LAY_DANH_MUC_KHOA_HOC: 'LAY_DANH_MUC_KHOA_HOC',
  LAY_DANH_DANH_SACH_KHOA_HOC_THEO_DANH_MUC: 'LAY_DANH_DANH_SACH_KHOA_HOC_THEO_DANH_MUC',
  LAY_DANH_SACH_KHOA_HOC: 'LAY_DANH_SACH_KHOA_HOC',
  LAY_DANH_SACH_KHOA_HOC_PHAN_TRANG: 'LAY_DANH_SACH_KHOA_HOC_PHAN_TRANG',
  LAY_THONG_TIN_KHOA_HOC: 'LAY_THONG_TIN_KHOA_HOC',
  LAY_THONG_TIN_KHOA_HOC_TIM_KIEM: 'LAY_THONG_TIN_KHOA_HOC_TIM_KIEM',
  
  THEM_KHOA_HOC: 'THEM_KHOA_HOC',
  UPLOAD_HINH_ANH_KHOA_HOC: 'UPLOAD_HINH_ANH_KHOA_HOC',
 
} 